"""Agregar prioridad a tareas

Revision ID: 56b45f708e4c
Revises: 3a34fc22ad79
Create Date: 2026-07-29 14:19:22.082010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56b45f708e4c'
down_revision: Union[str, Sequence[str], None] = '3a34fc22ad79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tareas', sa.Column('prioridad', sa.String(length=20), nullable=False, server_default="Media"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tareas', 'prioridad')
    # ### end Alembic commands ###
