"""Agregar fecha_vencimiento a tareas

Revision ID: 9ba7644c8363
Revises: 56b45f708e4c
Create Date: 2026-07-29 15:09:59.131229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ba7644c8363'
down_revision: Union[str, Sequence[str], None] = '56b45f708e4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tareas', sa.Column('fecha_vencimiento', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tareas', 'fecha_vencimiento')
    # ### end Alembic commands ###
